# Generated by Django 5.0.3 on 2024-04-22 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
        ('trolley_app', '0005_remove_trolley_food_remove_trolley_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='trolley',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='trolley_app.trolley'),
        ),
    ]
