# Generated by Django 5.0.3 on 2024-04-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
        ('recipe_app', '0001_initial'),
        ('trolley_app', '0002_trolley_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolley',
            name='food',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trolley', to='food_app.food'),
        ),
        migrations.AlterField(
            model_name='trolley',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trolley',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trolley', to='recipe_app.recipe'),
        ),
    ]
